[package]
name = "tokentrip_auctions"
version = "0.0.1"
edition = "2024.alpha"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet" }

# Se añade la dependencia al paquete de experiences para poder usar el struct ExperienceNFT
tokentrip_experiences = { local = "../tokentrip_experiences" }

[addresses]
tokentrip_auctions = "0x0"
tokentrip_experience = "0x7c58a8f35419a88cdb406993397ea17b68f7e082b79ad187b4d6e084025b4267"
tokentrip_token = "0xed46584d450fc173a7796cdbc934248df25f0d46700a3a852fb025f1d9a000b3"
tokentrip_dao = "0xfa1a5a8c8f307f3bac14acd7b182ffef7fa5c28fc7fa905877127944e0339448"

worhmhole = "0x6fb10cdb7aa299e9a4308752dadecb049ff55a892de92992a1edbd7912b3d6da"